# Generated by Django 6.0.6 on 2026-07-04 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PRO', 'Programado'), ('ECU', 'En Curso'), ('CAN', 'Cancelado'), ('FIN', 'Finalizado')], default='PRO', max_length=3)),
                ('category', models.CharField(blank=True, choices=[('ACA', 'Académico'), ('CUL', 'Cultural'), ('DEP', 'Deportes'), ('ASA', 'Asamblea'), ('PAR', 'Parche'), ('OTR', 'Otro')], max_length=3, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['datetime_start'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
