# Generated by Django 6.0.6 on 2026-07-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_borrowed', models.DateTimeField()),
                ('datetime_return', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Borrowing',
                'verbose_name_plural': 'Borrowings',
            },
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('BAL', 'Balones'), ('RAQ', 'Raquetas'), ('MES', 'Mesas'), ('JUR', 'Juegos recreativos'), ('JUM', 'Juegos de mesa'), ('OTS', 'Otros')], max_length=3)),
                ('faculty', models.CharField(blank=True, choices=[('ART', 'Artes'), ('CCS', 'Ciencias'), ('CIA', 'Ciencias Agrarias'), ('CIE', 'Ciencias Económicas'), ('CHS', 'Ciencias Humanas'), ('DER', 'Derecho, Ciencias Políticas y Sociales'), ('ENF', 'Enfermería'), ('ING', 'Ingeniería'), ('MED', 'Medicina'), ('MVZ', 'Medicina Veterinaria y Zootecnia'), ('ODO', 'Odontología')], max_length=3, null=True)),
                ('state', models.CharField(choices=[('DIS', 'Disponible'), ('NDS', 'No Disponible'), ('RES', 'Reservado'), ('PRS', 'Prestado')], default='NDS', max_length=3)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Implement',
                'verbose_name_plural': 'Implements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_reserved', models.DateTimeField()),
                ('datetime_expiration', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
            },
        ),
    ]
