# Generated by Django 6.0.6 on 2026-07-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implement',
            name='state',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('NDS', 'No Disponible'), ('RES', 'Reservado'), ('PRE', 'Prestado')], default='NDS', max_length=3),
        ),
    ]
