services:
  backend:
    build:
      context: ./backend-undesparche
      dockerfile: Dockerfile
    container_name: django_api
    restart: unless-stopped
    command: >
      sh -c "python3 manage.py makemigrations users events inventory  &&
             python3 manage.py migrate &&
             python3 manage.py createroles &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      UNSUBSCRIBE_TOKEN_SALT: ${UNSUBSCRIBE_TOKEN_SALT}
    volumes:
      - ./backend-undesparche:/app
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles
      - ./backend-undesparche/firebase_credentials.json:/app/firebase_credentials.json:ro
    ports:
      - "8000:8000"
      - "587:587"

  frontend:
    build:
      context: ./frontend-undesparche
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  static_files:
  media_files:
